darkkitchen_xdr.c
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "darkkitchen.h"

bool_t
xdr_cuisine (XDR *xdrs, cuisine *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idCuisine))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomCuisine, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->adresse, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ville, 20))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_formulaire (XDR *xdrs, formulaire *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idClient))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomClient, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->mail, 40))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tel, 10))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->villeRes, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomResto, 30))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbResto))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->villeDest, 30))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_justificatif (XDR *xdrs, justificatif *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->assurance, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->formations, 30))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	 if (!xdr_formulaire (xdrs, &objp->formulaire))
		 return FALSE;
	 if (!xdr_justificatif (xdrs, &objp->justificatif))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_formule (XDR *xdrs, formule *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idFormule))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomFormule, 15))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbCommandeMax))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_formule (xdrs, &objp->formule))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date))
		 return FALSE;
	 if (!xdr_client (xdrs, &objp->client))
		 return FALSE;
	 if (!xdr_cuisine (xdrs, &objp->cuisine))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_livraison (XDR *xdrs, livraison *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->idLivraison))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomTypeLivraison, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chaine (XDR *xdrs, chaine *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listClients (XDR *xdrs, listClients objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 5,
		sizeof (chaine), (xdrproc_t) xdr_chaine))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listCuisines (XDR *xdrs, listCuisines objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 5,
		sizeof (chaine), (xdrproc_t) xdr_chaine))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listDemande (XDR *xdrs, listDemande objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 5,
		sizeof (chaine), (xdrproc_t) xdr_chaine))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listLocationEnCours (XDR *xdrs, listLocationEnCours objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 5,
		sizeof (chaine), (xdrproc_t) xdr_chaine))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listLivraison (XDR *xdrs, listLivraison objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 5,
		sizeof (chaine), (xdrproc_t) xdr_chaine))
		 return FALSE;
	return TRUE;
}
