darkkitchen_client.c
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "darkkitchen.h"


void
v1_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	void  *result_2;
	formulaire  ajoutclient_1_arg;
	int  *result_3;
	client  modifierclient_1_arg;
	int  *result_4;
	justificatif  modifierjustificatif_1_arg;
	void  *result_5;
	cuisine  ajoutcuisine_1_arg;
	int  *result_6;
	cuisine  modifiercuisine_1_arg;
	void  *result_7;
	formule  initformule_1_arg;
	int  *result_8;
	formule  modifierformule_1_arg;
	int  *result_9;
	formulaire  analysedemande_1_arg;
	char * *result_10;
	char *statusdemande_1_arg;
	int  *result_11;
	location  ajoutlocation_1_arg;
	int  *result_12;
	location  dellocation_1_arg;
	char * *result_13;
	cuisine  infocuisine_1_arg;
	char * *result_14;
	formule  infoformule_1_arg;
	void  *result_15;
	livraison  inittypelivraison_1_arg;
	char * *result_16;
	livraison  infolivraison_1_arg;
	int  *result_17;
	livraison  selectiontypelivraison_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, V1, cuisine_v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = ajoutclient_1(&ajoutclient_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = modifierclient_1(&modifierclient_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = modifierjustificatif_1(&modifierjustificatif_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = ajoutcuisine_1(&ajoutcuisine_1_arg, clnt);
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = modifiercuisine_1(&modifiercuisine_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = initformule_1(&initformule_1_arg, clnt);
	if (result_7 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = modifierformule_1(&modifierformule_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = analysedemande_1(&analysedemande_1_arg, clnt);
	if (result_9 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = statusdemande_1((void*)&statusdemande_1_arg, clnt);
	if (result_10 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = ajoutlocation_1(&ajoutlocation_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = dellocation_1(&dellocation_1_arg, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = infocuisine_1(&infocuisine_1_arg, clnt);
	if (result_13 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = infoformule_1(&infoformule_1_arg, clnt);
	if (result_14 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = inittypelivraison_1(&inittypelivraison_1_arg, clnt);
	if (result_15 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = infolivraison_1(&infolivraison_1_arg, clnt);
	if (result_16 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = selectiontypelivraison_1(&selectiontypelivraison_1_arg, clnt);
	if (result_17 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	v1_1 (host);
exit (0);
}
